export interface IRestaurant {
  ResPushID:string,
  ResName:string,
  ImageLogo:string,
  ImageURL:string;
  OwnerName:string,
  Rate:number,
  Phone:number,
  Mood:string[],
  Type:string[],
  IsActivated:boolean,
  Branches:{
    BranchId:string,
    Address:string,
    LocName:string,
    Workinghours:string
  },
  Menu:{
  },
  Offers:{
    Description:string,
    Expires:any,
    PromoCode:string
  }
}
